<?php

/**
 * Implements hook_theme().
 */
function partner_dashboard_theme($existing, $type, $theme, $path) {
  return [
    'property_listing_form' => [
      'variables' => [
        'title' => NULL,
        'form' => []
      ],
      'template' => 'property-listing-form',
    ],
    'vehicle_listing_form' => [
      'variables' => [
        'title' => NULL,
        'form' => []
      ],
      'template' => 'vehicle-listing-form',
    ],
    'property_basic_form' => [
      'render element' => 'form',
      'template' => 'property-basic-form',
    ],
    'vehicle_selling_form' => [
      'render element' => 'form',
      'template' => 'vehicle-selling-form',
    ],
  ];
}