<?php
use Drupal\Core\Mail\MailFormatHelper;

/**
 * Implements hook_theme().
 */
function partner_dashboard_theme($existing, $type, $theme, $path) {
  return [
    'property_listing_form' => [
      'variables' => [
        'title' => NULL,
        'form' => []
      ],
      'template' => 'property-listing-form',
    ],
    'vehicle_listing_form' => [
      'variables' => [
        'title' => NULL,
        'form' => []
      ],
      'template' => 'vehicle-listing-form',
    ],
    'property_basic_form' => [
      'render element' => 'form',
      'template' => 'property-basic-form',
    ],
    'vehicle_selling_form' => [
      'render element' => 'form',
      'template' => 'vehicle-selling-form',
    ],
  ];
}



/**
 * Implements hook_mail().
 */
function partner_dashboard_mail($key, &$message, $params) {

  switch ($key) {

    // User Thank You Mail
    case 'user_thank_you':
      $message['subject'] = $params['subject'];
      $message['body'][] = MailFormatHelper::htmlToText($params['body']);
      break;

    // Admin Enquiry Mail
    case 'admin_enquiry':
      $message['subject'] = $params['subject'];
      $message['body'][] = MailFormatHelper::htmlToText($params['body']);
      break;
  }
}